<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
        $this->load->model('Member_model');
    }

    public function index()
    {
		if($this->session->userdata('logined') && $this->session->userdata('logined') == true) 
		{
			if($this->session->userdata('username') == 'admin'){
				redirect('Admin');
			}
			else{
				redirect('Home/user');
			}
		}
		
		if(!$this->input->post()) 
		{
			redirect('Home');
		}
		else
		{
			$cek_login_admin = $this->Admin_model->cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
			$cek_login_member = $this->Member_model->cek_login(
				$this->input->post('username'),
				$this->input->post('password')
				);
			if(!empty($cek_login_admin))
			{
				$this->session->set_userdata('username',$cek_login_admin->username);
				$this->session->set_userdata('logined',true);				
				redirect('Admin');
			}
			else if(!empty($cek_login_member))
			{
				$this->session->set_userdata('username',$cek_login_member->id_member);
				$this->session->set_userdata('logined',true);				
				redirect('Home/user');
			}
			else 
			{
				$this->session->set_flashdata('gagal', "<div class=\"col-md-12\"><div class=\"alert alert-danger\" id=\"alert\">Email atau Password salah</div></div>");
				redirect('Home');
			}
		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');
		redirect('/');
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */